server:
  port: 5050

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/programming_languages?createDatabaseIfNotExist=true
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    rest:
      base-path: /api

